# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform a BLAST-like sequence similarity search
#' 
#' @param query_table A DataFrame
#' @param db_table A DataFrame
#' @param output_file A string
#' @param maxAccepts An integer
#' @param maxRejects An integer
#' @param minIdentity A double
#' @param strand A string
pre_blast <- function(query_table, db_table, output_file, maxAccepts = 1L, maxRejects = 16L, minIdentity = 0.75, strand = "both") {
    invisible(.Call('_blaster_pre_blast', PACKAGE = 'blaster', query_table, db_table, output_file, maxAccepts, maxRejects, minIdentity, strand))
}

#' Read the contents of a Fasta file into a DataFrame
#' 
#' @param filename A string
#' @param filter A string
#' @export
read_fasta <- function(filename, filter = "") {
    .Call('_blaster_read_fasta', PACKAGE = 'blaster', filename, filter)
}

