# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_fasta <- function(filename, by, split = TRUE) {
    .Call(`_blaster_filter_fasta`, filename, by, split)
}

read_fasta <- function(filename, keep_ids = TRUE) {
    .Call(`_blaster_read_fasta`, filename, keep_ids)
}

